## enable or disable automatic update checks
update_check = false

## the maximum number of lines the interface should take up
## when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "inline_height"
inline_height_shell_up_key_binding = 10

## Show numeric shortcuts (1..9) beside list items in the TUI
## set to false to hide the moving numbers if you find them distracting
show_numeric_shortcuts = false

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
  "^(cd|ls|ll)$",
]

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command,
## whereas tab will put the command in the prompt for editing.
## If set to false, both enter and tab will place the command in the prompt for editing.
## This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = false

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "aws",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

## Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

[keys]
# Defaults to true. If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
scroll_exits = false

# Defaults to true. The left arrow key will exit the TUI when scrolling before the first character
exit_past_line_start = false

# Defaults to true. The right arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
accept_past_line_end = false

# Defaults to false. The left arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
accept_past_line_start = false

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true

[ai]
enabled = false

