call pathogen#infect()

syntax enable
filetype plugin indent on
set nocompatible

"if filereadable("$VIMRUNTIME/mswin.vim")
"  :so $VIMRUNTIME/mswin.vim
"endif
":behave mswin

set background=dark
if has("gui_running")
  set nu
  if has("gui_macvim")
    set guifont=Liberation\ Mono\ for\ Powerline:h9
  else
    set guifont=FiraCode\ Nerd\ Font\ 10
  endif
  set guioptions-=T
  set lines=50
  set columns=140
  let g:airline_powerline_fonts = 1
else
  let g:airline_powerline_fonts = 1
  set t_Co=256
endif

colorscheme vividchalk
autocmd ColorScheme * hi Search ctermbg=DarkBlue

set shiftwidth=2
set tabstop=2
set expandtab

set noautowrite
set hidden
set autoindent smartindent
set smarttab
set history=200
set incsearch
set ignorecase
set hlsearch
set showmatch
set nobackup

set backspace=indent,eol,start

set encoding=utf-8
set laststatus=2

set wildignore=*.swp,*.zip,.svn/*,*.class,*.jar

set tags=./tags;/

vmap <Tab> >gv
vmap <S-Tab> <gv

let g:buffergator_viewport_split_policy = "B"
let g:buffergator_autoexpand_on_split = 0
let g:buffergator_split_size = 0
let g:buffergator_sort_regime = "mru"

let g:ctrlp_mruf_case_sensitive = 0
let g:ctrlp_mruf_last_entered = 1
let g:ctrlp_dotfiles = 0
let g:ctrlp_working_path_mode = 0

let g:syntastic_perl_efm_program = 'perl /usr/share/vim/vimfiles/perl-support/scripts/efm_perl.pl -c'

let g:vimwiki_list = [
  \ {'path': '~/Documents/notes', 'ext': '.md'},
  \ {'path': '~/dbtool/doc', 'ext': '.txt', 'index': 'README'}
  \ ]

let g:tagbar_type_vimwiki = {
  \ 'ctagstype': 'wiki',
  \ 'sort': 0,
  \ 'kinds' : [
    \ 'h:header',
  \ ]
  \}

let tlist_vimwiki_settings = "wiki;h:header"
let g:vimwiki_global_ext=0

vnoremap <leader>q :<c-u>call <SID>QuoteLines()<cr>
vnoremap <leader>j :<c-u>call <SID>JoinLines()<cr>
vmap <leader>s <leader>qgv<leader>j

function! s:JoinLines()
  silent! execute "normal! gv:\<c-u>'<,'>-1s/\\v$/,/g\<cr>gvJ"
endfunction

function! s:QuoteLines()
  silent! execute "normal! gv:s/\\v(^\\s*)([^[:space:]].{-})(\\s*$)/\\1'\\2'\\3/\<CR>"
endfunction

nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

" Fix copy and paste
map <S-Insert> "+gP
cmap <S-Insert> <C-R>+
exe 'inoremap <script> <S-Insert>' paste#paste_cmd['i']

" Select All (Visual)
noremap <C-A> ggVG

"This allows for change paste motion cp{motion}
"Borrowed from http://stackoverflow.com/questions/2471175/vim-replace-word-with-contents-of-paste-buffer
nmap <silent> cp :set opfunc=ChangePaste<CR>g@
function! ChangePaste(type, ...)
    silent exe "normal! `[v`]\"_c"
    silent exe "normal! p"
endfunction

let g:ackprg = "rg --vimgrep"
let g:ack_default_opts = "--smart-case"
let g:ack_autoclose = 0
let g:ackhighlight = 1


let g:vim_markdown_folding_style_pythonic = 1

let g:airline#extensions#taglist#enabled = 0

set nomodeline

