#!/bin/sh

cd $HOME

ROFI_EXECUTABLE="~/bin/rofi"

exec $ROFI_EXECUTABLE -modi combi,dirs,filebrowser,drun,ssh -show combi -combi-modi drun,ssh,dirs -modes "combi,dirs:/home/abatkin/bin/dirs.py" -combi-hide-mode-prefix "$@"
